### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by Yamilquery** [bjunc/apollo-link-phx-ws#4]
With Expo React Native app I get:

```
TransformError: /Users/asd/Documents/grvty/Bark/bark-client/node_modules/apollo-link-phx-ws/dist/PhoenixWebSocketLink.js: Unknown plugin "transform-runtime" specified in "/Users/asd/Documents/grvty/Bark/bark-client/node_modules/apollo-link-phx-ws/.babelrc" at 0, attempted to resolve relative to "/Users/asd/Documents/grvty/Bark/bark-client/node_modules/apollo-link-phx-ws"

ABI19_0_0RCTFBQuickPerformanceLoggerConfigureHooks
ABI19_0_0RCTFBQuickPerformanceLoggerConfigureHooks
ABI19_0_0RCTFBQuickPerformanceLoggerConfigureHooks
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>

```

This is my package.json dependencies:

`"dependencies": {
    "apollo-cache-inmemory": "^1.1.0",
    "apollo-client": "^2.0.2",
    "apollo-client-preset": "^1.0.2",
    "apollo-link": "^1.0.3",
    "apollo-link-context": "^1.0.1",
    "apollo-link-http": "^1.1.0",
    "apollo-link-phx-ws": "^0.3.4",
    "apollo-link-set-context": "^0.5.4",
    "apollo-link-ws": "^1.0.2",
    "apollo-phoenix-websocket": "^0.6.2",
    "apollo-utilities": "^1.0.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "credit-card-type": "^6.1.0",
    "expo": "^20.0.0",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.14",
    "point-in-polygon": "^1.0.1",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-apollo": "^2.0.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-config": "^0.6.1",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-masked-text": "^1.6.4",
    "react-native-router-flux": "4.0.0-beta.20",
    "react-native-sentry": "^0.14.0",
    "react-native-svg": "^6.0.0-rc1",
    "react-native-swiper": "^1.5.13",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^7.0.4",
    "redux-observable": "0.15.0",
    "redux-persist": "^4.10.0",
    "redux-persist-transform-encrypt": "^1.0.2",
    "rxjs": "^5.4.3",
    "sentry-expo": "https://github.com/HazAT/sentry-expo#4c6d0e5ea658757833b5432a710efa892f6c3c14",
    "subscriptions-transport-ws": "^0.9.4"
  },`

**Comment by bjunc** [comment]
Did you get this working?  I'm not sure why it would cause an issue for you, but `babel-plugin-transform-runtime` is a dev dependency.

**Comment by Yamilquery** [comment]
It seems to be a bug with babel, searching a little bit I found that remove .babelrc works fine.

**Comment by bjunc** [comment]
Okay, great.  I'll close the issue then.

**Comment by Yamilquery** [comment]
Ok, it would be great if you'll could remove the .babelrc from this module.

Thank you so much!

**Comment by bjunc** [comment]
I don't think that would be possible, as it's being used as the config for transpiling.  I'm not sure why you would have a conflict with it though.  Are you installing via `npm`?
